### ISSUE TITLE
Can't Set DPID in UI

### ISSUE THREAD

**Issue by Ktmi** [kytos-ng/sdntrace_cp#121]
Can't seem to set the DPID for the trace in the web UI. I'm using firefox 128.0.3. Same thing happens with `sdntrace`. Issue for sdntrace at kytos-ng/sdntrace#91

**Comment by viniarck** [comment]
@Ktmi, on firefox 128.0.2 on Linux it's working for me, and on google-chrome too:

![20240805_113628](https://github.com/user-attachments/assets/c7d0f928-6dde-40cf-8e89-d41c3e6aafbd)

What errors are you getting in the console? Check out if you've got the latest `ui` and if it has been built recently.
