### ISSUE TITLE
feat: adapt code to support `dl_vlan`  when it has a mask

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/sdntrace_cp#78]
`flow_manager` is being updated to support `dl_vlan` value/mask on this issue https://github.com/kytos-ng/flow_manager/issues/132

[Related PR](https://github.com/kytos-ng/flow_manager/pull/135) on flow_manager has just landed

**Comment by viniarck** [comment]
Issue discussion regarding mask and payload is going on [here](https://github.com/kytos-ng/kytos/issues/318#) for the record

**Comment by gretelliz** [comment]
@viniarck, Currently `dl_vlan` in flows supports mask, while `dl_vlan` in packet args is an integer into [1, 4095]. We shouldn't support a mask in the payload input, so this issue can be closed, right?

**Comment by viniarck** [comment]
> @viniarck, Currently `dl_vlan` in flows supports mask, while `dl_vlan` in packet args is an integer into [1, 4095]. We shouldn't support a mask in the payload input, so this issue can be closed, right?

That's correct @gretelliz, yes no mask in the input. Also, looking into [unit test test_match_field_dl_vlan](https://github.com/kytos-ng/sdntrace_cp/blob/master/tests/unit/test_utils.py#L419-L421), it's also covering there, so the way it's converting and how the `value` is being passed looks good to me, feel free to close it.
